// LENS-DESIGN: headless family UI contract and real scan integration.
process.env.LINKLENSE_TEST_HEADLESS='1';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {fixture} from './fixture.mjs';
const require=createRequire(import.meta.url),base='http://127.0.0.1:4494',out=new URL('../test-output/design/',import.meta.url).pathname;
const server=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:'4494'},stdio:'pipe'});
const site=await fixture(),checks=[],errors=[];let browser;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function api(path,data){const r=await fetch(base+'/api/'+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json','X-LinkLense':'1'},...(data?{body:JSON.stringify(data)}:{})});assert.ok(r.ok);return r.json()}
function pass(id,detail){checks.push({id,detail});console.log(id+' '+detail)}
async function inspect(page,name){await page.evaluate(()=>document.fonts.ready);await pause(200);await page.screenshot({path:out+name+'.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' document overflow');await page.evaluate(await readFile(require.resolve('axe-core/axe.min.js'),'utf8'));const results=await page.evaluate(()=>axe.run());assert.deepEqual(results.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),[],name+' axe');}
try{
 await mkdir(out,{recursive:true});let health;for(let i=0;i<80;i++){try{health=await api('health');break}catch{await pause(100)}}assert.ok(health?.ok);
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);
 for(const theme of ['light','dark']){await page.getByLabel('Appearance',{exact:true}).selectOption(theme);for(const [w,h] of [[1440,1050],[375,812],[844,390]]){await page.setViewportSize({width:w,height:h});await inspect(page,`home-${theme}-${w}`)}}
 pass('LENS-01','Home: light/dark, desktop, mobile portrait and landscape; no axe violations or document overflow.');
 await page.setViewportSize({width:1440,height:1050});await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.getByLabel('Appearance',{exact:true}).selectOption('system');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 const second=await browser.newPage();await second.goto(base); // separate context: independent preference
 const sibling=await page.context().newPage();await sibling.goto(base);await page.getByLabel('Appearance',{exact:true}).selectOption('light');await sibling.waitForFunction(()=>document.documentElement.dataset.theme==='light');assert.equal(await sibling.getByLabel('Appearance',{exact:true}).inputValue(),'light');await sibling.close();await second.close();
 pass('LENS-02','Appearance persists, follows live OS changes in System mode, and synchronizes across tabs.');
 await page.locator('#start-url').fill('not-a-url');await page.getByRole('button',{name:'Start your first audit'}).click();assert.equal(await page.locator('dialog').evaluate(d=>d.open),false);
 await page.locator('#start-url').fill(site.url+'/second');await page.locator('#start-url').press('Enter');assert.equal(await page.locator('#site-url').inputValue(),site.url+'/second');await inspect(page,'setup-light-1440');await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'New audit',exact:true}).first().click();assert.equal(await page.locator('#site-url').inputValue(),'');await page.locator('#next').click();assert.match(await page.locator('#url-error').textContent(),/valid HTTP/);await page.getByRole('button',{name:'Close dialog'}).click();
 pass('LENS-03','Home URL validates and carries through on Enter; New audit resets URL and reports validation errors.');
 await page.getByRole('button',{name:'Scan history',exact:true}).click();await inspect(page,'history-empty-light-1440');await page.getByRole('link',{name:'LinkLense home'}).click();assert.ok(await page.locator('#start-url').isVisible());
 await page.getByLabel('Appearance',{exact:true}).selectOption('dark');await page.setViewportSize({width:375,height:812});await page.getByRole('button',{name:'New audit',exact:true}).first().click();await page.locator('#site-url').fill(site.url+'/second');await inspect(page,'setup-dark-375');await page.locator('#next').click();await page.getByRole('radio',{name:'Current page'}).check();await inspect(page,'scope-dark-375');await page.locator('#next').click();await inspect(page,'review-dark-375');await page.locator('#next').click();await page.waitForFunction(()=>!document.querySelector('dialog').open,null,{timeout:60000});assert.equal(await page.locator('.metric strong').first().innerText(),'2');
 pass('LENS-04','Mobile dark setup, scope, review and live current-page scan complete with both viewports.');
 // Rich results come from the real local scanner fixture, not manufactured UI data.
 const job=await api('jobs',{kind:'scan',url:site.url+'/',pages:[site.url+'/'],scope:'Current page',viewports:['Desktop','Mobile']});let result;
 for(let i=0;i<180;i++){const state=await api('jobs/'+job.id);if(state.status==='complete'){result=state.result;break}assert.notEqual(state.status,'error',state.error);await pause(500)}assert.ok(result);
 await page.evaluate(a=>localStorage.setItem('linklense-audits-v1',JSON.stringify([a])),result);await page.reload();
 for(const theme of ['light','dark']){await page.getByLabel('Appearance',{exact:true}).selectOption(theme);for(const [w,h] of [[1440,1050],[375,812],[844,390]]){await page.setViewportSize({width:w,height:h});await inspect(page,`report-${theme}-${w}`);if(w===375)assert.ok((await page.locator('.site-info').boundingBox()).width>200,'Mobile scope details retain a readable width')}}
 pass('LENS-05','Real report: all six theme/viewport combinations pass axe and horizontal-overflow checks.');
 await page.getByRole('tab',{name:'All links'}).click();await page.locator('#viewport-filter').selectOption('Mobile');assert.ok(await page.locator('tbody tr').count());assert.ok((await page.locator('tbody tr td:nth-child(4)').allTextContents()).every(t=>t==='Mobile'));await page.locator('#finding-search').fill('no-such-record-xyz');assert.equal(await page.locator('tbody tr').count(),0);await page.getByRole('button',{name:'Clear filters'}).click();await page.locator('[data-detail]').first().click();await inspect(page,'evidence-dark-844');await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('tab',{name:'Page coverage'}).click();await inspect(page,'coverage-dark-844');await page.getByRole('button',{name:'Scan history',exact:true}).click();await inspect(page,'history-dark-844');await page.getByRole('link',{name:'LinkLense home'}).click();assert.equal(await page.locator('[data-history]').count(),1);await page.locator('[data-history]').first().click();assert.ok(await page.locator('.metrics').isVisible());
 pass('LENS-06','Viewport filter, search/no results/reset, evidence, page coverage, history and home recents work.');
 await page.setViewportSize({width:375,height:812});await page.getByRole('link',{name:'LinkLense home'}).click();await page.evaluate(()=>{const items=[...document.querySelectorAll('body *')].filter(e=>!e.closest('svg')).map(e=>[e,parseFloat(getComputedStyle(e).fontSize)*2]);for(const [e,size] of items)e.style.fontSize=size+'px'}); // Double each computed size once, without exponential inheritance.
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'enlarged text overflow');await page.screenshot({path:out+'text-enlarged-375.png',fullPage:true});await page.reload();
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.primary').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.className),'skip');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'main');
 pass('LENS-07','Text enlargement reflows, reduced motion disables transitions, and keyboard skip link reaches main.');
 assert.deepEqual(errors,[]);await writeFile(out+'results.json',JSON.stringify({build:health.buildId,version:health.version,checks,errors},null,2));console.log('LENS design contract passed.');
}finally{await browser?.close();server.kill('SIGTERM');site.server.closeAllConnections();await new Promise(r=>site.server.close(r))}
