import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {readFile} from 'node:fs/promises';
import {fixture} from './fixture.mjs';
const site=await fixture(),base='http://127.0.0.1:4399',child=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:'4399'},stdio:'pipe'});let browser;
try{for(let i=0;i<60;i++){try{await fetch(base+'/api/health');break}catch{await new Promise(r=>setTimeout(r,100))}}
 const sample=JSON.parse(await readFile(new URL('../test-output/report.json',import.meta.url),'utf8'));
 const records=[{...sample,id:'first',url:'https://first.example/'},{...sample,id:'second',url:'https://second.example/'}];
 browser=await chromium.launch();const context=await browser.newContext(),page=await context.newPage();await page.goto(base);await page.evaluate(records=>localStorage.setItem('linklense-audits-v1',JSON.stringify(records)),records);await page.reload();const other=await context.newPage();await other.goto(base);await other.getByRole('button',{name:'Scan history',exact:true}).click();
 await page.getByRole('button',{name:'Scan history',exact:true}).click();await page.getByRole('button',{name:'Back to home'}).click();await page.getByRole('heading',{name:/Every link/}).waitFor();await page.getByRole('button',{name:'Scan history',exact:true}).click();await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('heading',{name:/Every link/}).waitFor();await page.getByRole('button',{name:'Scan history',exact:true}).click();
 await page.locator('[data-delete-history="first"]').click();await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.locator('tbody tr').count(),2);
 await page.locator('[data-delete-history="first"]').click();await page.getByRole('button',{name:'Delete report',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});assert.equal(await page.locator('tbody tr').count(),1);await other.locator('[data-delete-history="first"]').waitFor({state:'detached'});
 // Storage write failure must not claim successful deletion.
 await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='linklense-audits-v1')throw Error('Storage denied');return window.originalSetItem.call(this,k,v)}});
 await page.getByRole('button',{name:'Clear history',exact:true}).click();await page.locator('#delete-confirm').click();await page.waitForFunction(()=>document.querySelector('#delete-error')?.textContent.includes('could not be updated'));assert.match(await page.locator('#delete-error').innerText(),/could not be updated/);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('linklense-audits-v1')).length),1);await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.evaluate(()=>Storage.prototype.setItem=window.originalSetItem);
 await page.getByRole('button',{name:'Clear history',exact:true}).click();await page.locator('#delete-confirm').click();await page.getByRole('heading',{name:'No audits yet.'}).waitFor();await other.getByRole('heading',{name:'No audits yet.'}).waitFor();await page.getByRole('button',{name:'Go to home'}).click();await page.getByRole('button',{name:'Start your first audit'}).waitFor();
 // Completing a scan from the other tab must not resurrect removed records.
 await other.getByRole('button',{name:'New audit',exact:true}).last().click();await other.locator('#site-url').fill(site.url+'/second');await other.locator('#next').click();await other.getByRole('radio',{name:'Current page'}).check();await other.locator('#next').click();await other.locator('#next').click();await other.waitForFunction(()=>!document.querySelector('dialog').open,null,{timeout:60000});assert.equal(await other.evaluate(()=>JSON.parse(localStorage.getItem('linklense-audits-v1')).length),1);assert.ok(await other.evaluate(()=>JSON.parse(localStorage.getItem('linklense-audits-v1')).every(a=>!['first','second'].includes(a.id))));
 await other.getByRole('button',{name:'Scan history',exact:true}).click();await other.setViewportSize({width:390,height:844});assert.equal(await other.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 console.log('History regression passed: home navigation, cancel deletion, individual deletion, clear all, storage-failure recovery, cross-tab synchronization, no resurrection, and mobile reflow.');
}finally{await browser?.close();child.kill('SIGTERM');site.server.closeAllConnections();await new Promise(r=>site.server.close(r))}
