process.env.LINKLENSE_TEST_HEADLESS='1';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
import {chromium} from 'playwright';
import {fixture} from './fixture.mjs';
import {spawn} from 'node:child_process';
import {readFile,mkdir} from 'node:fs/promises';
const port=4391,base=`http://127.0.0.1:${port}`,site=await fixture();const processServer=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port)},stdio:'pipe'});let browser;const errors=[];
async function api(p,data,method=data?'POST':'GET'){const r=await fetch(base+'/api/'+p,{method,headers:{'X-LinkLense':'1','Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const v=await r.json();if(!r.ok)throw Error(v.error);return v}
async function job(data){const {id}=await api('jobs',data);for(let i=0;i<200;i++){const r=await api('jobs/'+id);if(r.status==='complete')return r.result;if(r.status==='error')throw Error(r.error);await new Promise(r=>setTimeout(r,350))}throw Error('Job test timeout')}
try{for(let i=0;i<50;i++){try{await api('health');break}catch{await new Promise(r=>setTimeout(r,100))}}let cross=await fetch(base+'/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(cross.status,403);const discovery=await job({kind:'discover',url:site.url+'/'});assert.ok(discovery.pages.length>=2);assert.ok(!site.requests.includes('/logout'));const result=await job({kind:'scan',url:site.url+'/',pages:[site.url+'/'],scope:'Current page'});assert.equal(result.pages.length,1);assert.equal(result.sampleData,false);const find=(id,v='Desktop')=>result.assets.find(a=>a.selector==='#'+id&&a.viewport===v);assert.ok(find('good').loaded);assert.equal(find('good').issues.length,0);assert.ok(find('broken').issues.some(i=>i.code==='http-failure'));assert.ok(find('broken').issues.some(i=>i.code==='missing-link-name'));for(const [id,code] of [['redirect','redirect'],['generic','generic-link-name'],['fragment','missing-fragment'],['mail','destination-unverified'],['keyboard','keyboard-unreachable'],['empty','scripted-destination'],['denied','destination-unverified'],['action','destination-unverified']])assert.ok(find(id).issues.some(i=>i.code===code),id+' '+code);assert.equal(find('valid-fragment').issues.length,0);assert.equal(find('image-name').accessibleName,'Photo gallery');assert.ok(result.assets.some(a=>a.selector.includes('shadow-link')));assert.ok(find('disclosure'));assert.ok(find('good','Mobile'));assert.ok(!site.requests.includes('/logout'));console.log('Scanner passed: status, redirects, fragments, semantics, keyboard, protocols, guarded actions, shadow DOM, disclosures, both viewports.');
browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto(base);assert.equal(await page.getByText('Personal workspace').count(),0);assert.equal(await page.getByText('DEMO',{exact:true}).count(),0);await page.evaluate(a=>localStorage.setItem('linklense-audits-v1',JSON.stringify([a])),result);await page.reload();await page.evaluate(await readFile(require.resolve('axe-core/axe.min.js'),'utf8'));const desktopAxe=await page.evaluate(()=>axe.run());assert.deepEqual(desktopAxe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);await page.locator('[data-detail]').first().click();await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('tab',{name:'All links'}).click();await page.locator('#type-filter').selectOption('missing-link-name');assert.ok(await page.locator('tbody tr').count()>0);await page.getByRole('button',{name:'Export report'}).click();await mkdir(new URL('../test-output/',import.meta.url),{recursive:true});for(const ext of['html','csv','json','pdf']){const wait=page.waitForEvent('download');await page.locator(`[data-export=${ext}]`).click();const download=await wait;await download.saveAs(new URL(`../test-output/report.${ext}`,import.meta.url).pathname)}const pdf=await readFile(new URL('../test-output/report.pdf',import.meta.url));assert.equal(pdf.subarray(0,4).toString(),'%PDF');await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('tab',{name:'Overview',exact:true}).click();await page.screenshot({path:new URL('../test-output/dashboard.png',import.meta.url).pathname,fullPage:true});await page.getByRole('button',{name:'New audit',exact:true}).last().click();await page.locator('#site-url').fill(site.url+'/second');await page.locator('#next').click();await page.getByRole('radio',{name:'Current page'}).check();await page.locator('#next').click();await page.locator('#next').click();await page.waitForFunction(()=>!document.querySelector('dialog').open,null,{timeout:60000});assert.match(await page.locator('.site-info').innerText(),/Current page/);assert.equal(await page.locator('.metric strong').first().innerText(),'2');await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.evaluate(await readFile(require.resolve('axe-core/axe.min.js'),'utf8'));const mobileAxe=await page.evaluate(()=>axe.run());assert.deepEqual(mobileAxe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);await page.screenshot({path:new URL('../test-output/mobile.png',import.meta.url).pathname,fullPage:true});
const report=await browser.newPage();report.on('pageerror',e=>errors.push(e.message));await report.goto(new URL('../test-output/report.html',import.meta.url).href);await report.evaluate(await readFile(require.resolve('axe-core/axe.min.js'),'utf8'));const reportAxe=await report.evaluate(()=>axe.run());assert.deepEqual(reportAxe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);const all=await report.locator('tbody tr:visible').count();await report.locator('[data-category=broken]').click();assert.ok(await report.locator('tbody tr:visible').count()<all);await report.locator('#issue-type').selectOption('missing-link-name');const overlap=await report.locator('tbody tr:visible').count();assert.ok(overlap>0);await report.locator('#viewport').selectOption('Mobile');assert.ok(await report.locator('tbody tr:visible').count()<overlap);await report.locator('#q').fill('nothing-matches-this');assert.equal(await report.locator('tbody tr:visible').count(),0);await report.locator('#reset').click();assert.equal(await report.locator('tbody tr:visible').count(),all);await report.locator('#expand').click();assert.ok(await report.locator('tbody details[open]').count()>0);const csvWait=report.waitForEvent('download');await report.locator('#download-filtered').click();assert.match((await csvWait).suggestedFilename(),/filtered/);assert.deepEqual(errors,[]);console.log('UI/export passed: current-page live run, category/type/viewport filters, overlapping findings, evidence, CSV/HTML/JSON/PDF downloads, standalone HTML interactivity, responsive layout.');
// Session confirmation rejects a visible login form, accepts signed-in content and retains cookies.
const session=await api('sessions',{url:site.url+'/login'});await assert.rejects(()=>api(`sessions/${session.id}/confirm`,{}),/sign-in|Sign-in|sign in/i);await api(`sessions/${session.id}`,null,'DELETE');console.log('Authentication rejected an incomplete login and cleaned up its browser.');
const connected=await api('sessions',{url:site.url+'/account'});await api(`sessions/${connected.id}/confirm`,{});const privateResult=await job({kind:'scan',url:site.url+'/account',pages:[site.url+'/protected'],sessionId:connected.id});assert.equal(privateResult.access,'private');assert.ok(privateResult.assets.some(a=>a.accessibleName==='Private destination'));await api(`sessions/${connected.id}`,null,'DELETE');console.log('Authenticated scan retained session cookies and inspected protected images.');
const cancelled=await api('jobs',{kind:'scan',url:site.url+'/',pages:[site.url+'/']});await api('jobs/'+cancelled.id,null,'DELETE');assert.equal((await api('jobs/'+cancelled.id)).status,'cancelled');console.log('Cancellation passed.');
}finally{await browser?.close();processServer.kill('SIGTERM');site.server.closeAllConnections();await new Promise(r=>site.server.close(r));}
