import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {sessions,closeSession} from '../src/scanner.js';
process.env.PORT='4396';process.env.LINKLENSE_TEST_HEADLESS='1';
const {server}=await import('../server.js');const base='http://127.0.0.1:4396',target='https://www.saucedemo.com/',out=new URL('../validation-output/saucedemo-e2e/',import.meta.url);await mkdir(out,{recursive:true});
let browser;const evidence=[];const errors=[];
async function record(data){evidence.push(data);await writeFile(new URL('results.json',out),JSON.stringify(evidence,null,2));console.log(JSON.stringify(data));}
try{
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);const health=await(await fetch(base+'/api/health')).json();assert.equal(health.restartRequired,false);await record({check:'running version',buildId:health.buildId,version:health.version});
 for(const [viewports,scope] of [[['Desktop'],'current'],[['Mobile'],'current'],[['Desktop','Mobile'],'current'],[['Desktop','Mobile'],'all']]){
  await page.getByRole('button',{name:/Start your first audit|New audit/}).last().click();await page.locator('#site-url').fill(target);await page.getByRole('radio',{name:'Requires sign-in'}).check();
  const sessionResponse=page.waitForResponse(r=>r.url()===base+'/api/sessions'&&r.request().method()==='POST');await page.getByRole('button',{name:'Open sign-in browser'}).click();const {id}=await(await sessionResponse).json();const login=sessions.get(id).page;
  await page.getByRole('button',{name:'Confirm completed sign-in'}).click();await page.locator('#url-error').filter({hasText:'sign-in form'}).waitFor();
  await login.getByPlaceholder('Username').fill('standard_user');await login.getByPlaceholder('Password').fill('secret_sauce');await login.getByRole('button',{name:'Login',exact:true}).click();await login.getByText('Products',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Confirm completed sign-in'}).click();await page.getByRole('button',{name:'Session connected'}).waitFor();assert.match(await page.locator('#site-url').inputValue(),/inventory.html/);assert.ok(login.isClosed());assert.equal(sessions.get(id).headless,true);assert.match(await sessions.get(id).page.evaluate(()=>navigator.userAgent),/HeadlessChrome/);
  await page.locator('#next').click();if(scope==='all'||viewports.length===1&&viewports[0]==='Desktop'){await page.getByRole('radio',{name:'Select pages'}).check();await page.getByRole('button',{name:'Discover website pages'}).click();await page.getByRole('heading',{name:'Choose your audit scope'}).waitFor({timeout:1800000});const choices=await page.locator('[data-select]').count();assert.ok(choices>=7,'Expected inventory and six product pages');await record({check:'scripted product-page discovery',pages:choices});}await page.getByRole('radio',{name:scope==='all'?'Entire website':'Current page'}).check();await page.locator('#next').click();
  for(const v of ['Desktop','Mobile'])await page.getByRole('checkbox',{name:v+' Web App'}).setChecked(viewports.includes(v));
  await page.locator('#next').click();await page.waitForFunction(()=>!document.querySelector('dialog').open,null,{timeout:1800000});
  const result=await page.evaluate(()=>JSON.parse(localStorage.getItem('linklense-audits-v1'))[0]);assert.equal(result.buildId,health.buildId);assert.deepEqual(result.viewports,viewports);assert.ok(scope==='all'?result.pages.length>7:result.pages.length===1);assert.equal(result.scope,scope==='all'?'Entire website (discovered pages)':'Current page');assert.ok(result.assets.length>0);const broken=result.assets.filter(a=>a.issues.some(i=>i.severity==='broken'));
  assert.equal(broken.length,0,JSON.stringify(broken));const products=result.assets.filter(a=>/^View details for /.test(a.accessibleName));assert.ok(products.length>=12*viewports.length);assert.ok(products.every(a=>a.interactionVerified&&a.loaded&&a.status==='pass'&&a.finalURL.includes('/inventory-item.html?id=')),JSON.stringify(products.map(a=>({name:a.name,status:a.status,reason:a.reason,finalURL:a.finalURL}))));assert.ok(result.pageResults.every(p=>p.status==='checked'));assert.equal(await page.locator('.metric strong').nth(1).innerText(),'0');
  await writeFile(new URL(scope+'-'+viewports.join('-')+'.json',out),JSON.stringify(result,null,2));await record({check:'real dashboard sign-in and audit',scope,pages:result.pages.length,viewports,observations:result.assets.length,verifiedProductLinks:products.length,broken:broken.length,buildId:result.buildId,coverageNotes:result.coverage.gaps.length});
 }
 // Inspect the UI's saved history and verify exports contain the same results.
 await page.getByRole('button',{name:'Export report'}).click();const downloadEvent=page.waitForEvent('download');await page.locator('[data-export=json]').click();const download=await downloadEvent;await download.saveAs(new URL('ui-export.json',out).pathname);await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'Scan history',exact:true}).click();assert.equal(await page.locator('tbody tr').count(),4);await page.getByRole('button',{name:'Back to home'}).click();await page.getByRole('heading',{name:/Every link/}).waitFor();await page.screenshot({path:new URL('dashboard.png',out).pathname,fullPage:true});assert.deepEqual(errors,[]);
 await record({check:'history, Home, JSON download, dashboard errors',status:'passed',savedReports:4});
 // The website session expires after the user confirms it but before the scan starts.
 await page.getByRole('button',{name:'New audit',exact:true}).last().click();await page.locator('#site-url').fill(target);await page.getByRole('radio',{name:'Requires sign-in'}).check();
 const expireResponse=page.waitForResponse(r=>r.url()===base+'/api/sessions'&&r.request().method()==='POST');await page.getByRole('button',{name:'Open sign-in browser'}).click();const expiredId=(await(await expireResponse).json()).id;const expiryLogin=sessions.get(expiredId).page;
 await expiryLogin.getByPlaceholder('Username').fill('standard_user');await expiryLogin.getByPlaceholder('Password').fill('secret_sauce');await expiryLogin.getByRole('button',{name:'Login',exact:true}).click();await expiryLogin.getByText('Products',{exact:true}).waitFor();await page.getByRole('button',{name:'Confirm completed sign-in'}).click();await page.getByRole('button',{name:'Session connected'}).waitFor();await page.locator('#next').click();await page.getByRole('radio',{name:'Current page'}).check();await page.locator('#next').click();
 const background=sessions.get(expiredId).page;await background.getByRole('button',{name:'Open Menu'}).click();await background.getByText('Logout',{exact:true}).click();await background.getByRole('button',{name:'Login',exact:true}).waitFor();
 await page.locator('#next').click();await page.waitForFunction(()=>!document.querySelector('dialog').open,null,{timeout:60000});await page.locator('.site-strip').getByText('Sign-in required',{exact:true}).waitFor();const expiredReport=await page.evaluate(()=>JSON.parse(localStorage.getItem('linklense-audits-v1'))[0]);assert.equal(expiredReport.assets.length,0);assert.ok(expiredReport.pageResults.every(p=>p.status==='unverified'));assert.deepEqual(errors,[]);await record({check:'actual website logout after confirmation',status:'passed',visibleResult:'Sign-in required'});

}finally{await browser?.close();for(const id of sessions.keys())await closeSession(id);await new Promise(r=>server.close(r));}
