import assert from 'node:assert/strict';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');if(req.url==='/missing'){res.statusCode=404;return res.end('<h1>404 Not found</h1>')}if(req.url==='/ok')return res.end('OK');res.end(`<h1>Responsive app</h1><main></main><script>document.querySelector('main').innerHTML=innerWidth<600?'<a id="mobile-only" href="/missing">Mobile offers</a>':'<a id="desktop-only" href="/ok">Desktop offers</a>'</script>`)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const site='http://127.0.0.1:'+server.address().port,base='http://127.0.0.1:4398';
const child=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:'4398'},stdio:'pipe'});let browser;
async function api(path,data){const r=await fetch(base+'/api/'+path,{method:data?'POST':'GET',headers:{'X-LinkLense':'1','Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const v=await r.json();if(!r.ok)throw Error(v.error);return v}
async function job(viewports){const {id}=await api('jobs',{kind:'scan',url:site,pages:[site],viewports});for(let i=0;i<200;i++){const j=await api('jobs/'+id);if(j.status==='complete')return j.result;if(j.status==='error')throw Error(j.error);await new Promise(r=>setTimeout(r,100))}throw Error('Timeout')}
try{for(let i=0;i<60;i++){try{await api('health');break}catch{await new Promise(r=>setTimeout(r,100))}}
for(const viewports of [[],['Tablet'],['Mobile','Mobile']])await assert.rejects(()=>job(viewports),/Select Desktop/);
const desktop=await job(['Desktop']);assert.deepEqual(desktop.viewports,['Desktop']);assert.equal(desktop.pageResults.length,1);assert.equal(desktop.assets[0].selector,'#desktop-only');
const both=await job(['Desktop','Mobile']);assert.ok(both.assets.some(a=>a.viewport==='Mobile'&&a.selector==='#mobile-only'&&a.status==='broken'));assert.ok(both.assets.some(a=>a.viewport==='Desktop'&&a.selector==='#desktop-only'&&a.status==='pass'));
browser=await chromium.launch();const page=await browser.newPage();await page.goto(base);await page.getByRole('button',{name:'Start your first audit'}).click();await page.locator('#site-url').fill(site);await page.locator('#next').click();await page.getByRole('radio',{name:'Current page'}).check();await page.locator('#next').click();await page.getByRole('checkbox',{name:'Desktop Web App'}).uncheck();await page.getByRole('checkbox',{name:'Mobile Web App'}).uncheck();await page.locator('#next').click();assert.match(await page.locator('#viewport-error').innerText(),/at least one/);await page.getByRole('checkbox',{name:'Mobile Web App'}).check();await page.locator('#back').click();await page.locator('#next').click();assert.equal(await page.getByRole('checkbox',{name:'Desktop Web App'}).isChecked(),false);await page.locator('#next').click();await page.waitForFunction(()=>!document.querySelector('dialog').open,null,{timeout:60000});const audit=await page.evaluate(()=>JSON.parse(localStorage.getItem('linklense-audits-v1'))[0]);assert.deepEqual(audit.viewports,['Mobile']);assert.ok(audit.assets.every(a=>a.viewport==='Mobile'));assert.equal(audit.assets[0].selector,'#mobile-only');assert.match(await page.locator('.site-info').innerText(),/Mobile Web App/);assert.doesNotMatch(await page.locator('.site-info').innerText(),/Desktop/);await page.getByRole('tab',{name:'Page coverage'}).click();assert.match(await page.locator('.matrix').innerText(),/1 \/ 1/);
await page.getByRole('button',{name:'Export report'}).click();const pending=page.waitForEvent('download');await page.locator('[data-export=html]').click();const download=await pending;const stream=await download.createReadStream();let html='';for await(const chunk of stream)html+=chunk;assert.ok(html.includes('Mobile Web App'));assert.ok(!html.includes('· Desktop & mobile ·'));
console.log('Viewport regression passed: desktop only, mobile only, both with independent page initialization, invalid/empty selection, selection retained on Back, accurate coverage denominator, and exported scope.');
}finally{await browser?.close();child.kill('SIGTERM');server.closeAllConnections();await new Promise(r=>server.close(r))}
